apiVersion: v1
kind: Service
metadata:
  name: tdee-cal-service
spec:
  type: NodePort
  ports:
  - name: TCP
    port: 80
    targetPort: 5000
    nodePort: 31000
    protocol: TCP
  selector:
    app: tdee-cal